import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
{/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
*/}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bar">
          <Link href='/search'>검색</Link>
          <Link href='/menu'>메뉴</Link>
          <Link href='/'>홈</Link>
          <Link href='/scrap'>스크랩</Link>
          <Link href='/my'>마이</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
